<a href="https://colab.research.google.com/github/shyamalkar/ML_project/blob/main/ML_Project_sonar_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd # import pandas
import numpy as np # import numpy
import matplotlib as plt # import matplotlib
import seaborn as sns # import sns
from sklearn.model_selection import train_test_split # import train test split
from sklearn.linear_model import LogisticRegression # import logistics regression algo
from sklearn.svm import SVC # alternative algo
from sklearn.metrics import accuracy_score # import accuracy score.

In [2]:
sonar_data = pd.read_csv("Copy of sonar data.csv", header=None) # use header=None when lack of columns names. and it's help to create columns names.

sonar_data.head(-1)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,0.0272,0.0378,0.0488,0.0848,0.1127,0.1103,0.1349,0.2337,0.3113,0.3997,...,0.0091,0.0045,0.0043,0.0043,0.0098,0.0054,0.0051,0.0065,0.0103,M
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M

In [3]:
sonar_data.shape # it tell us how many rows and columns have in this dataset .

(208, 61)

In [4]:
sonar_data.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60],
      dtype='int64')

In [5]:
sonar_data.describe() # all math like count to max apply in all columns all rows.

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [6]:
print("columns",len(sonar_data.columns)) #check how many columns i has ?

print("rows",len(sonar_data)) # check how many rows i has

columns 61
rows 208

In [7]:
print("Print rows and columns",sonar_data.shape)# how many rows and columns

Print rows and columns (208, 61)

In [8]:
sonar_data[60].value_counts() # "How many times does each unique value occur in column 60?"
# it showing M = Mine - 111
# and R rock number 97.
#total = 208
# When i check rows and columns it showing me 61 rows and 207 columns and but when i count manually it showing me 208 so one data mismatch .
# so we gonna use isnull().sum(),
# what do isnull sum ?
# isnull sum checks every cell and if any missing value has then fill with True and if any missing value don't have that means false.
# then counts all the True (missing values) for each columns.
# and sum() counts all True (missing)values for each column . and finally ad value.

60
M    111
R     97
Name: count, dtype: int64

In [9]:
print(sonar_data[60].isnull()) # it use for any missing data has then it showing True and if any missing value don't have then it's called False.

0      False
1      False
2      False
3      False
4      False
       ...
203    False
204    False
205    False
206    False
207    False
Name: 60, Length: 208, dtype: bool

In [10]:
sonar_data.groupby(60).sum() # Columns no 60 has only 2 types like M and R. and after group the data M and R all values are sum .

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,3.8838,5.0554,5.6299,7.1892,9.6254,12.4169,14.2478,16.6314,23.6976,27.8634,...,2.1481,1.7775,1.2924,1.3525,1.1014,0.9894,0.8686,1.0057,0.9652,0.7692
R,2.1823,2.9394,3.4872,4.0204,6.0167,9.3337,11.0755,11.4068,13.3270,15.4545,...,1.1942,1.0139,0.9351,0.9232,0.8310,0.7207,0.7580,0.6477,0.6866,0.5843

`separating data and labels`

In [11]:
# This code is doing one of the most important steps in a machine-learning project: separating features (input) and labels (output).

X = sonar_data.drop(columns=60) # That means , remove columns 60 from the dataset, so you are removing the M/R column
y = sonar_data[60] # This selects only columns 60 . This is the target level that model need to predict.

print(X) # is the input data

         0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

         9   ...      50      51      52      53      54      55      56  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040

         57      58      59
0    0.0084  0.0090  0.0032
1    0.0049  0.0052  0.0044
2    0.0164  0.0095  0.0078
3    0.0044  0.0040  0.0117
4    0.0048  0.0107  0.0094
..      ...     ...     ...
203  0.0115  0.0193  0.0157
204  0.0032  0.0062  0.0067
205  0.0138  0.0077  0.0031
206  0.0079  0.0036  0.0048
207  0.0036  0.0061  0.0115

[208 rows x 60 columns]

In [12]:
print(y) # y is the label variable where we want to predict the answer .

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

In [13]:
# Training and Test Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y, random_state=1)

# X_train The feature data that will be used for train the ML model.
# Suppose i have 207 samples and use 10% for testing .
# approximately , 207 samples, 186 samples -> X_train, 21 samples -> X_test .
# so X_train contains the 60 sonar measurements for the trainig samples.

# x_test means contains the feature data that the model hasn't seen during training .
# y train contains the correct answer corresponding to X_train.
# X_train sample       y_train
#     ↓                  ↓
#60 sonar values  →     M
#60 sonar values  →     R
#60 sonar values  →     R
#60 sonar values  →     M

# train_test_split() this is a function from sklearn, and randomly divide your dataset into training data and testing data.
# X contains your feature / input data.
# y contains the target / label
# predict label is M and R , and X - sonar measurements and y contains Mine and Rock.

# test_size = 0.1 , this is particularly important . 0.1 means 10% of the data will be used for testing. and the 90% used for training . that means total 208 and 10% out that means 186 training nad 21 for testing .

# stratify=y this is another very important parameter, especially for your rock / mine classification
# stratif=y means keep approximately the same proportion of M and R both training and testing datasets.
# if suppose your original dataset looks like: M=111, R=97, The dataset contains roughly , M = 53% , R = 47% .
# without stratification, random splitting could accidently produce something like:
# Training: M = 100, R = 86, Testing: M = 11 , R = 11

# It might be okay, but random splitting doesn't guarantee the proportions.
# with stratify=y it looks like =  Original = M ≈ 53% ,R ≈ 47% , - > Training ,M ≈ 53% ,R ≈ 47% , -> Testing M ≈ 53%, R ≈ 47%

# That is why stratify=y is commonly usefull for classification ptobelem.

# random_state = anynumber,  this controls the randomness of the split . random_state= anynumber means , it fixes the random split so you get the same result every time you run the code.  so everytime you run it, you get the same random split .
# and there is nothing about sepcial about 42 , you could use , any number .

# so random_state = any_number a seed that makes random results reproducible.

In [14]:
print("Original Data shape",X.shape)
print("X_train_shape", X_train.shape)
print("X_test_shape", X_test.shape)

Original Data shape (208, 60)
X_train_shape (187, 60)
X_test_shape (21, 60)

In [15]:
print("Training data",X_train) # it is a trianing data and we see that how the data looks like ?

Training data          0       1       2       3       4       5       6       7       8   \
115  0.0414  0.0436  0.0447  0.0844  0.0419  0.1215  0.2002  0.1516  0.0818
38   0.0123  0.0022  0.0196  0.0206  0.0180  0.0492  0.0033  0.0398  0.0791
56   0.0152  0.0102  0.0113  0.0263  0.0097  0.0391  0.0857  0.0915  0.0949
123  0.0270  0.0163  0.0341  0.0247  0.0822  0.1256  0.1323  0.1584  0.2017
18   0.0270  0.0092  0.0145  0.0278  0.0412  0.0757  0.1026  0.1138  0.0794
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
140  0.0412  0.1135  0.0518  0.0232  0.0646  0.1124  0.1787  0.2407  0.2682
5    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105
154  0.0117  0.0069  0.0279  0.0583  0.0915  0.1267  0.1577  0.1927  0.2361
131  0.1150  0.1163  0.0866  0.0358  0.0232  0.1267  0.2417  0.2661  0.4346
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328

         9   ...      50      51      52      53      54      55      56  \
115  0.1975  ...  0.0222  0.0045  0.0136  0.0113  0.0053  0.0165  0.0141
38   0.0475  ...  0.0149  0.0125  0.0134  0.0026  0.0038  0.0018  0.0113
56   0.1504  ...  0.0048  0.0049  0.0041  0.0036  0.0013  0.0046  0.0037
123  0.2122  ...  0.0197  0.0189  0.0204  0.0085  0.0043  0.0092  0.0138
18   0.1520  ...  0.0045  0.0084  0.0010  0.0018  0.0068  0.0039  0.0120
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
140  0.2058  ...  0.0798  0.0376  0.0143  0.0272  0.0127  0.0166  0.0095
5    0.3039  ...  0.0104  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057
154  0.2169  ...  0.0039  0.0053  0.0029  0.0020  0.0013  0.0029  0.0020
131  0.5378  ...  0.0228  0.0099  0.0065  0.0085  0.0166  0.0110  0.0190
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065

         57      58      59
115  0.0077  0.0246  0.0198
38   0.0058  0.0047  0.0071
56   0.0011  0.0034  0.0033
123  0.0094  0.0105  0.0093
18   0.0132  0.0070  0.0088
..      ...     ...     ...
140  0.0225  0.0098  0.0085
5    0.0027  0.0051  0.0062
154  0.0062  0.0026  0.0052
131  0.0141  0.0068  0.0086
203  0.0115  0.0193  0.0157

[187 rows x 60 columns]

In [16]:
print("Label data",y_train) # y_train is a label data

Label data 115    M
38     R
56     R
123    M
18     R
      ..
140    M
5      R
154    M
131    M
203    M
Name: 60, Length: 187, dtype: object

In [17]:
model = LogisticRegression() # we store the algorithm in model variable.

# You can also use SVM , SVM also give good prediction.

In [18]:
# training the Logistics Regression model with training data
model.fit(X_train, y_train) # fit means , train / learn from the data .  model.fit() is the learning stage.

# so i give the model X_train - sonar data and y_train - correct answer (R/M)
# The model try to learn the relationship sonar measuremets -> rock or mine.

# used for = Because before making predictions on new data, the model needs to learn from your training data.

LogisticRegression()

# Model Evaluation

In [20]:
# predicting the training data

X_train_prediction = model.predict(X_train) # "Now that you've learned from X_train, predict the labels of X_train." the model produce something like, 'R', 'M'. , these prediction are stored in: X_train_prediction
# to see how well the model performance on the training data.

# calculating the training accuracy ,
training_data_accuracy = accuracy_score(X_train_prediction, y_train) # accuracy_score() compares: model_prediction vs actual answer .  and the result store in training_data_accuracy .
#for example

#Prediction    Actual
#   R             R      ✓
#   M             M      ✓
#   R             M      ✗
#   M             M      ✓

# suppose 180 out of 186 predictions are correct:
# accuracy = 180/186
#        = 96.8% and this result store in training_data_accuracy
# use for to measure - To measure how accurately your model predicts the training data.


# print the training accuracy

In [21]:
print("Accuracy on training data:", training_data_accuracy) # this simply displays the result :
# acuracy on training data 0.83 means 83%

Accuracy on training data: 0.8342245989304813

In [22]:
# now comes the important part
# accuracy on test data

X_test_prediction = model.predict(X_test) # give the model X_test, which contains data that it did't use during training .
test_data_accuracy = accuracy_score(X_test_prediction, y_test)


#This tells us how well the model performs on unseen data. This is much more useful for judging whether your model can generalize .

# predicting values on actual values .

# Prediction    Actual
# R             R      ✓
# M             M      ✓
# M             R      ✗
# R             R      ✓

# then we calculate the percentage of correct predictions.

In [23]:
print("Äccuracy on test data", test_data_accuracy) # print the test accuracy .
# if accuracy on test data: 0.7619 that means 76.19% accuracy.

Äccuracy on test data 0.7619047619047619

In [24]:
import joblib

# Replace 'model' with the actual variable name of your trained model
# Running this line creates 'sonar_model.pkl' in your current folder
joblib.dump(model, 'sonar_model.pkl')

['sonar_model.pkl']